
import { Collection, CollectionCategory, CollectionItem } from './types';

// Helper data for country-based collections
const countries: { code: string, name: string }[] = [
    { code: 'af', name: 'Afghanistan' }, { code: 'al', name: 'Albania' }, { code: 'dz', name: 'Algeria' },
    { code: 'ar', name: 'Argentina' }, { code: 'au', name: 'Australia' }, { code: 'at', name: 'Austria' },
    { code: 'be', name: 'Belgium' }, { code: 'bo', name: 'Bolivia' }, { code: 'br', name: 'Brazil' },
    { code: 'bg', name: 'Bulgaria' }, { code: 'kh', name: 'Cambodia' }, { code: 'ca', name: 'Canada' },
    { code: 'cl', name: 'Chile' }, { code: 'cn', name: 'China' }, { code: 'co', name: 'Colombia' },
    { code: 'cr', name: 'Costa Rica' }, { code: 'hr', name: 'Croatia' }, { code: 'cu', name: 'Cuba' },
    { code: 'cz', name: 'Czech Republic' }, { code: 'dk', name: 'Denmark' }, { code: 'ec', name: 'Ecuador' },
    { code: 'eg', name: 'Egypt' }, { code: 'fi', name: 'Finland' }, { code: 'fr', name: 'France' },
    { code: 'de', name: 'Germany' }, { code: 'gr', name: 'Greece' }, { code: 'gt', name: 'Guatemala' },
    { code: 'hu', name: 'Hungary' }, { code: 'is', name: 'Iceland' }, { code: 'in', name: 'India' },
    { code: 'id', name: 'Indonesia' }, { code: 'ir', name: 'Iran' }, { code: 'iq', name: 'Iraq' },
    { code: 'ie', name: 'Ireland' }, { code: 'il', name: 'Israel' }, { code: 'it', name: 'Italy' },
    { code: 'jm', name: 'Jamaica' }, { code: 'jp', name: 'Japan' }, { code: 'jo', name: 'Jordan' },
    { code: 'ke', name: 'Kenya' }, { code: 'kr', name: 'South Korea' }, { code: 'kw', name: 'Kuwait' },
    { code: 'lb', name: 'Lebanon' }, { code: 'ly', name: 'Libya' }, { code: 'lt', name: 'Lithuania' },
    { code: 'lu', name: 'Luxembourg' }, { code: 'my', name: 'Malaysia' }, { code: 'mx', name: 'Mexico' },
    { code: 'ma', name: 'Morocco' }, { code: 'nl', name: 'Netherlands' }, { code: 'nz', name: 'New Zealand' },
    { code: 'ng', name: 'Nigeria' }, { code: 'no', name: 'Norway' }, { code: 'pk', name: 'Pakistan' },
    { code: 'py', name: 'Paraguay' }, { code: 'pe', name: 'Peru' }, { code: 'ph', name: 'Philippines' },
    { code: 'pl', name: 'Poland' }, { code: 'pt', name: 'Portugal' }, { code: 'qa', name: 'Qatar' },
    { code: 'ro', name: 'Romania' }, { code: 'ru', name: 'Russia' }, { code: 'sa', name: 'Saudi Arabia' },
    { code: 'rs', name: 'Serbia' }, { code: 'sg', name: 'Singapore' }, { code: 'sk', name: 'Slovakia' },
    { code: 'si', name: 'Slovenia' }, { code: 'za', name: 'South Africa' }, { code: 'es', name: 'Spain' },
    { code: 'lk', name: 'Sri Lanka' }, { code: 'se', name: 'Sweden' }, { code: 'ch', name: 'Switzerland' },
    { code: 'sy', name: 'Syria' }, { code: 'tw', name: 'Taiwan' }, { code: 'th', name: 'Thailand' },
    { code: 'tn', name: 'Tunisia' }, { code: 'tr', name: 'Turkey' }, { code: 'ua', name: 'Ukraine' },
    { code: 'ae', name: 'United Arab Emirates' }, { code: 'gb', name: 'United Kingdom' }, { code: 'us', name: 'United States' },
    { code: 'uy', name: 'Uruguay' }, { code: 've', name: 'Venezuela' }, { code: 'vn', name: 'Vietnam' },
];

const createCountryItems = (type: 'coin' | 'banknote', ownedCodes: string[]): CollectionItem[] => {
  return countries.map(country => ({
    id: `${type}-${country.code}`,
    name: country.name,
    owned: ownedCodes.includes(country.code),
    rarity: 'Country',
    imageUrl: `https://flagcdn.com/w80/${country.code}.png`
  }));
};

export const INITIAL_COLLECTIONS: Collection[] = [
  // =================================================================
  // BEARBRICK COLLECTIONS
  // =================================================================
  {
    id: 'bearbrick-bape-play',
    name: 'Bearbrick BAPE PLAY Series 1',
    description: 'A special collaboration series from 2007 featuring A Bathing Ape\'s iconic designs.',
    category: CollectionCategory.BEARBRICK,
    items: [
      { id: 'bape-s1-pattern', name: 'BAPE PLAY Pattern (Star Camo)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S1' },
      { id: 'bape-s1-flag', name: 'BAPE PLAY Flag (BAPE STA)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S1' },
      { id: 'bape-s1-animal', name: 'BAPE PLAY Animal (Shark Hoodie)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S1' },
      { id: 'bape-s1-bape-sta', name: 'BAPE PLAY BAPE STA Logo', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S1' },
      { id: 'bape-s1-baby-milo', name: 'BAPE PLAY Baby Milo', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S1' },
      { id: 'bape-s1-general', name: 'BAPE PLAY General', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S1' },
      { id: 'bape-s1-secret1', name: 'BAPE PLAY Secret (ABC Camo Green)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S1' },
      { id: 'bape-s1-secret2', name: 'BAPE PLAY Secret (ABC Camo Blue)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S1' },
      { id: 'bape-s1-secret3', name: 'BAPE PLAY Secret (ABC Camo Pink)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S1' },
    ],
  },
  {
    id: 'bearbrick-bape-play-s2',
    name: 'Bearbrick BAPE PLAY Series 2',
    description: 'The second installment of the BAPE PLAY collaboration series with Medicom Toy.',
    category: CollectionCategory.BEARBRICK,
    items: [
      { id: 'bape-s2-pattern', name: 'BAPE PLAY Pattern (1st Camo)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S2' },
      { id: 'bape-s2-flag', name: 'BAPE PLAY Flag (UK Camo)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S2' },
      { id: 'bape-s2-animal', name: 'BAPE PLAY Animal (Tiger Hoodie)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S2' },
      { id: 'bape-s2-ape-head', name: 'BAPE PLAY Ape Head Logo', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S2' },
      { id: 'bape-s2-baby-milo', name: 'BAPE PLAY Baby Milo (Standing)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S2' },
      { id: 'bape-s2-kaws', name: 'BAPE PLAY KAWS Companion Skull', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S2' },
      { id: 'bape-s2-secret1', name: 'BAPE PLAY Secret (Black Camo)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S2' },
      { id: 'bape-s2-secret2', name: 'BAPE PLAY Secret (Grey Camo)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S2' },
    ],
  },
  {
    id: 'bearbrick-bape-play-s3',
    name: 'Bearbrick BAPE PLAY Series 3',
    description: 'The third installment of the BAPE PLAY collaboration series, featuring new designs and artists.',
    category: CollectionCategory.BEARBRICK,
    items: [
      { id: 'bape-s3-pattern', name: 'BAPE PLAY Pattern (Milo Camo)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S3' },
      { id: 'bape-s3-flag', name: 'BAPE PLAY Flag (US Camo)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S3' },
      { id: 'bape-s3-animal', name: 'BAPE PLAY Animal (Panda Hoodie)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S3' },
      { id: 'bape-s3-college', name: 'BAPE PLAY College Logo', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S3' },
      { id: 'bape-s3-milo-friends', name: 'BAPE PLAY Baby Milo & Friends', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S3' },
      { id: 'bape-s3-teriyaki', name: 'BAPE PLAY Teriyaki Boyz', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S3' },
      { id: 'bape-s3-secret1', name: 'BAPE PLAY Secret (Milo Camo Multi)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S3' },
      { id: 'bape-s3-secret2', name: 'BAPE PLAY Secret (Wonder Woman)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S3' },
    ],
  },
  {
    id: 'bearbrick-bape-play-s4',
    name: 'Bearbrick BAPE PLAY Series 4',
    description: 'The fourth and final installment of the original BAPE PLAY collaboration series.',
    category: CollectionCategory.BEARBRICK,
    items: [
      { id: 'bape-s4-pattern', name: 'BAPE PLAY Pattern (Digital Camo)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S4' },
      { id: 'bape-s4-flag', name: 'BAPE PLAY Flag (World Wide BAPE)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S4' },
      { id: 'bape-s4-animal', name: 'BAPE PLAY Animal (Cow Hoodie)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S4' },
      { id: 'bape-s4-bapeman', name: 'BAPE PLAY Bapeman', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S4' },
      { id: 'bape-s4-milo-dj', name: 'BAPE PLAY Baby Milo DJ', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S4' },
      { id: 'bape-s4-nerd', name: 'BAPE PLAY N.E.R.D', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S4' },
      { id: 'bape-s4-secret1', name: 'BAPE PLAY Secret (SpongeBob)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S4' },
      { id: 'bape-s4-secret2', name: 'BAPE PLAY Secret (Pharrell)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=BAPE+S4' },
    ],
  },
  {
    id: 'bearbrick-disney-classics',
    name: 'Bearbrick Disney Classics',
    description: 'A magical collection of Bearbricks featuring beloved classic Disney characters.',
    category: CollectionCategory.BEARBRICK,
    items: [
      { id: 'disney-mickey', name: 'Bearbrick 100% Mickey Mouse (Vintage)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=Mickey' },
      { id: 'disney-minnie', name: 'Bearbrick 100% Minnie Mouse (Vintage)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=Minnie' },
      { id: 'disney-donald', name: 'Bearbrick 100% Donald Duck', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=Donald' },
      { id: 'disney-goofy', name: 'Bearbrick 100% Goofy', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=Goofy' },
      { id: 'disney-pinocchio', name: 'Bearbrick 100% Pinocchio', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=Pinocchio' },
      { id: 'disney-jiminy', name: 'Bearbrick 100% Jiminy Cricket', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=Jiminy' },
      { id: 'disney-oswald', name: 'Bearbrick 100% Oswald the Lucky Rabbit', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=Oswald' },
      { id: 'disney-secret-steamboat', name: 'Bearbrick 100% Steamboat Willie (Monochrome)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=Steamboat' },
    ],
  },
  {
    id: 'bearbrick-s46',
    name: 'Bearbrick Series 46',
    description: 'The 46th installment of the iconic Bearbrick blind box series by Medicom Toy.',
    category: CollectionCategory.BEARBRICK,
    items: [
      { id: 's46-basic', name: 'Bearbrick 100% Series 46 Basic @', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S46+Basic' },
      { id: 's46-jellybean', name: 'Bearbrick 100% Series 46 Jellybean (Glow)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S46+Jelly' },
      { id: 's46-pattern', name: 'Bearbrick 100% Series 46 Pattern (Garbage Pail Kids)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S46+GPK' },
      { id: 's46-flag', name: 'Bearbrick 100% Series 46 Flag (Brazil)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S46+Brazil' },
      { id: 's46-horror', name: 'Bearbrick 100% Series 46 Horror (The Nun II)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S46+Nun' },
      { id: 's46-sf', name: 'Bearbrick 100% Series 46 SF (RoboCop)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S46+RoboCop' },
      { id: 's46-cute', name: 'Bearbrick 100% Series 46 Cute (Despicable Me 4)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S46+Minion' },
      { id: 's46-animal', name: 'Bearbrick 100% Series 46 Animal (Lupin the 3rd)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S46+Lupin' },
      { id: 's46-artist1', name: 'Bearbrick 100% Series 46 Artist (Yen Town Market)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S46+Artist' },
      { id: 's46-artist2', name: 'Bearbrick 100% Series 46 Artist (AE-DC)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S46+Artist' },
      { id: 's46-secret-grendizer', name: 'Bearbrick 100% Series 46 Secret (Grendizer)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S46+Secret' },
      { id: 's46-secret-the-kid-laroi', name: 'Bearbrick 100% Series 46 Secret (The Kid Laroi)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S46+Secret' },
      { id: 's46-secret-inunokagayaki', name: 'Bearbrick 100% Series 46 Secret (Inunokagayaki)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S46+Secret' },
    ],
  },
  {
    id: 'bearbrick-s45',
    name: 'Bearbrick Series 45',
    description: 'The 45th installment of the iconic Bearbrick blind box series by Medicom Toy.',
    category: CollectionCategory.BEARBRICK,
    items: [
      { id: 's45-basic', name: 'Bearbrick 100% Series 45 Basic @', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S45+Basic' },
      { id: 's45-jellybean', name: 'Bearbrick 100% Series 45 Jellybean (Glow)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S45+Jelly' },
      { id: 's45-pattern', name: 'Bearbrick 100% Series 45 Pattern (The Mandalorian)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S45+Mando' },
      { id: 's45-flag', name: 'Bearbrick 100% Series 45 Flag (Greece)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S45+Greece' },
      { id: 's45-horror', name: 'Bearbrick 100% Series 45 Horror (The Silence of the Lambs)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S45+Lambs' },
      { id: 's45-sf', name: 'Bearbrick 100% Series 45 SF (Shin Ultraman)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S45+Ultra' },
      { id: 's45-cute', name: 'Bearbrick 100% Series 45 Cute (The Flintstones)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S45+Flint' },
      { id: 's45-animal', name: 'Bearbrick 100% Series 45 Animal (Gachapin & Mukku)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S45+Gacha' },
      { id: 's45-artist1', name: 'Bearbrick 100% Series 45 Artist (Black Adam)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S45+Artist' },
      { id: 's45-artist2', name: 'Bearbrick 100% Series 45 Artist (Dynamite Kid)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S45+Artist' },
      { id: 's45-secret-mandalorian', name: 'Bearbrick 100% Series 45 Secret (Grogu)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S45+Secret' },
      { id: 's45-secret-hanni', name: 'Bearbrick 100% Series 45 Secret (Hannibal Lecter Variant)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S45+Secret' },
      { id: 's45-secret-wwe', name: 'Bearbrick 100% Series 45 Secret (Hulk Hogan)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S45+Secret' },
    ],
  },
  {
    id: 'bearbrick-s44',
    name: 'Bearbrick Series 44',
    description: 'The 44th installment of the iconic Bearbrick blind box series by Medicom Toy.',
    category: CollectionCategory.BEARBRICK,
    items: [
      { id: 's44-basic', name: 'Bearbrick 100% Series 44 Basic B', rarity: 'Common', owned: true, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+Basic' },
      { id: 's44-jellybean', name: 'Bearbrick 100% Series 44 Jellybean', rarity: 'Common', owned: true, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+Jelly' },
      { id: 's44-pattern', name: 'Bearbrick 100% Series 44 Pattern (The Boys)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+Boys' },
      { id: 's44-flag', name: 'Bearbrick 100% Series 44 Flag (South Korea)', rarity: 'Common', owned: true, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+Korea' },
      { id: 's44-horror', name: 'Bearbrick 100% Series 44 Horror (The Shining)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+Shining' },
      { id: 's44-sf', name: 'Bearbrick 100% Series 44 SF (Terminator 2)', rarity: 'Uncommon', owned: true, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+T2' },
      { id: 's44-cute', name: 'Bearbrick 100% Series 44 Cute (Emily the Strange)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+Emily' },
      { id: 's44-animal', name: 'Bearbrick 100% Series 44 Animal (Cobra Kai)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+Cobra' },
      { id: 's44-artist1', name: 'Bearbrick 100% Series 44 Artist (Jean-Michel Basquiat)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+Artist' },
      { id: 's44-artist2', name: 'Bearbrick 100% Series 44 Artist (Kenny Scharf)', rarity: 'Rare', owned: true, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+Artist' },
      { id: 's44-secret-squidgame', name: 'Bearbrick 100% Series 44 Secret (Squid Game Guard)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+Secret' },
      { id: 's44-secret-strangerthings', name: 'Bearbrick 100% Series 44 Secret (Stranger Things)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+Secret' },
      { id: 's44-secret-moneyheist', name: 'Bearbrick 100% Series 44 Secret (Money Heist)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+Secret' },
      { id: 's44-supersecret-basquiat', name: 'Bearbrick 100% Series 44 Super Secret (Basquiat Variant)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S44+Secret' },
    ],
  },
  {
    id: 'bearbrick-s43',
    name: 'Bearbrick Series 43',
    description: 'The 43rd installment of the iconic Bearbrick blind box series by Medicom Toy.',
    category: CollectionCategory.BEARBRICK,
    items: [
        { id: 's43-basic', name: 'Bearbrick 100% Series 43 Basic @', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S43+Basic' },
        { id: 's43-jellybean', name: 'Bearbrick 100% Series 43 Jellybean', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S43+Jelly' },
        { id: 's43-pattern', name: 'Bearbrick 100% Series 43 Pattern (Powerpuff Girls)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S43+PPG' },
        { id: 's43-flag', name: 'Bearbrick 100% Series 43 Flag (France)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S43+France' },
        { id: 's43-horror', name: 'Bearbrick 100% Series 43 Horror (The Exorcist)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S43+Exorcist' },
        { id: 's43-sf', name: 'Bearbrick 100% Series 43 SF (WandaVision)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S43+Wanda' },
        { id: 's43-cute', name: 'Bearbrick 100% Series 43 Cute (Elmo)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S43+Elmo' },
        { id: 's43-animal', name: 'Bearbrick 100% Series 43 Animal (Monchhichi)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S43+Monch' },
        { id: 's43-artist1', name: 'Bearbrick 100% Series 43 Artist (NBA)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S43+Artist' },
        { id: 's43-artist2', name: 'Bearbrick 100% Series 43 Artist (Cobra Kai)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S43+Artist' },
        { id: 's43-secret-vision', name: 'Bearbrick 100% Series 43 Secret (Vision)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S43+Secret' },
        { id: 's43-secret-scarletwitch', name: 'Bearbrick 100% Series 43 Secret (Scarlet Witch)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S43+Secret' },
    ],
  },
  {
    id: 'bearbrick-s42',
    name: 'Bearbrick Series 42',
    description: 'The 42nd installment of the iconic Bearbrick blind box series by Medicom Toy.',
    category: CollectionCategory.BEARBRICK,
    items: [
      { id: 's42-basic', name: 'Bearbrick 100% Series 42 Basic @', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S42+Basic' },
      { id: 's42-jellybean', name: 'Bearbrick 100% Series 42 Jellybean (Glow)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S42+Jelly' },
      { id: 's42-pattern', name: 'Bearbrick 100% Series 42 Pattern (Minions)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S42+Minion' },
      { id: 's42-flag', name: 'Bearbrick 100% Series 42 Flag (Mexico)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S42+Mexico' },
      { id: 's42-horror', name: 'Bearbrick 100% Series 42 Horror (The Texas Chainsaw Massacre)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S42+TCM' },
      { id: 's42-sf', name: 'Bearbrick 100% Series 42 SF (Evangelion)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S42+Eva' },
      { id: 's42-cute', name: 'Bearbrick 100% Series 42 Cute (Tom and Jerry)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S42+T%26J' },
      { id: 's42-animal', name: 'Bearbrick 100% Series 42 Animal (Grateful Dead)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S42+Bear' },
      { id: 's42-artist1', name: 'Bearbrick 100% Series 42 Artist (Medicom Toy)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S42+Artist' },
      { id: 's42-artist2', name: 'Bearbrick 100% Series 42 Artist (Keith Haring)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S42+Artist' },
      { id: 's42-secret-jujutsu', name: 'Bearbrick 100% Series 42 Secret (Jujutsu Kaisen)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S42+Secret' },
      { id: 's42-secret-gates', name: 'Bearbrick 100% Series 42 Secret (The Gates)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S42+Secret' },
    ],
  },
  {
    id: 'bearbrick-s41',
    name: 'Bearbrick Series 41',
    description: 'The 41st installment of the iconic Bearbrick blind box series by Medicom Toy.',
    category: CollectionCategory.BEARBRICK,
    items: [
      { id: 's41-basic', name: 'Bearbrick 100% Series 41 Basic @', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S41+Basic' },
      { id: 's41-jellybean', name: 'Bearbrick 100% Series 41 Jellybean', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S41+Jelly' },
      { id: 's41-pattern', name: 'Bearbrick 100% Series 41 Pattern (The Boys)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S41+Boys' },
      { id: 's41-flag', name: 'Bearbrick 100% Series 41 Flag (Canada)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S41+Canada' },
      { id: 's41-horror', name: 'Bearbrick 100% Series 41 Horror (The Fly)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S41+Fly' },
      { id: 's41-sf', name: 'Bearbrick 100% Series 41 SF (Evangelion)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S41+Eva' },
      { id: 's41-cute', name: 'Bearbrick 100% Series 41 Cute (Tom and Jerry)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S41+T%26J' },
      { id: 's41-animal', name: 'Bearbrick 100% Series 41 Animal (Felix the Cat)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S41+Felix' },
      { id: 's41-artist1', name: 'Bearbrick 100% Series 41 Artist (Hajime Sorayama)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S41+Artist' },
      { id: 's41-artist2', name: 'Bearbrick 100% Series 41 Artist (Mika Ninagawa)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S41+Artist' },
      { id: 's41-secret-400', name: 'Bearbrick 100% Series 41 Secret (400%)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S41+Secret' },
      { id: 's41-secret-warhol', name: 'Bearbrick 100% Series 41 Secret (Andy Warhol)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S41+Secret' },
    ],
  },
  {
    id: 'bearbrick-s40',
    name: 'Bearbrick Series 40',
    description: 'The 40th installment of the iconic Bearbrick blind box series by Medicom Toy.',
    category: CollectionCategory.BEARBRICK,
    items: [
      { id: 's40-basic', name: 'Bearbrick 100% Series 40 Basic @', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S40+Basic' },
      { id: 's40-jellybean', name: 'Bearbrick 100% Series 40 Jellybean', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S40+Jelly' },
      { id: 's40-pattern', name: 'Bearbrick 100% Series 40 Pattern (Evangelion)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S40+Eva' },
      { id: 's40-flag', name: 'Bearbrick 100% Series 40 Flag (Japan)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S40+Japan' },
      { id: 's40-horror', name: 'Bearbrick 100% Series 40 Horror (The Shining)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S40+Shining' },
      { id: 's40-sf', name: 'Bearbrick 100% Series 40 SF (Black Adam)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S40+Adam' },
      { id: 's40-cute', name: 'Bearbrick 100% Series 40 Cute (Gremlins)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S40+Gremlin' },
      { id: 's40-animal', name: 'Bearbrick 100% Series 40 Animal (Billiken)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S40+Billiken' },
      { id: 's40-artist1', name: 'Bearbrick 100% Series 40 Artist (Andy Warhol)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S40+Artist' },
      { id: 's40-artist2', name: 'Bearbrick 100% Series 40 Artist (EXIT)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S40+Artist' },
      { id: 's40-secret-gizmo', name: 'Bearbrick 100% Series 40 Secret (Gizmo Variant)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S40+Secret' },
      { id: 's40-secret-ww84', name: 'Bearbrick 100% Series 40 Secret (Wonder Woman 1984)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S40+Secret' },
    ],
  },
  {
    id: 'bearbrick-s39',
    name: 'Bearbrick Series 39',
    description: 'The 39th installment of the iconic Bearbrick blind box series by Medicom Toy.',
    category: CollectionCategory.BEARBRICK,
    items: [
      { id: 's39-basic', name: 'Bearbrick 100% Series 39 Basic @', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S39+Basic' },
      { id: 's39-jellybean', name: 'Bearbrick 100% Series 39 Jellybean', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S39+Jelly' },
      { id: 's39-pattern', name: 'Bearbrick 100% Series 39 Pattern (BAPE)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S39+BAPE' },
      { id: 's39-flag', name: 'Bearbrick 100% Series 39 Flag (USA)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S39+USA' },
      { id: 's39-horror', name: 'Bearbrick 100% Series 39 Horror (Chucky)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S39+Chucky' },
      { id: 's39-sf', name: 'Bearbrick 100% Series 39 SF (John Wick)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S39+Wick' },
      { id: 's39-cute', name: 'Bearbrick 100% Series 39 Cute (Care Bears)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S39+Care' },
      { id: 's39-animal', name: 'Bearbrick 100% Series 39 Animal (Black Eye Patch)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S39+Animal' },
      { id: 's39-artist1', name: 'Bearbrick 100% Series 39 Artist (James Jean)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S39+Artist' },
      { id: 's39-artist2', name: 'Bearbrick 100% Series 39 Artist (Kaori Hinata)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S39+Artist' },
      { id: 's39-secret-unkle', name: 'Bearbrick 100% Series 39 Secret (Unkle)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S39+Secret' },
      { id: 's39-secret-johnwick', name: 'Bearbrick 100% Series 39 Secret (John Wick Chase)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S39+Secret' },
    ],
  },
  {
    id: 'bearbrick-s38',
    name: 'Bearbrick Series 38',
    description: 'The 38th installment of the iconic Bearbrick blind box series by Medicom Toy.',
    category: CollectionCategory.BEARBRICK,
    items: [
      { id: 's38-basic', name: 'Bearbrick 100% Series 38 Basic @', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S38+Basic' },
      { id: 's38-jellybean', name: 'Bearbrick 100% Series 38 Jellybean (Glow)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S38+Jelly' },
      { id: 's38-pattern', name: 'Bearbrick 100% Series 38 Pattern (Joker)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S38+Joker' },
      { id: 's38-flag', name: 'Bearbrick 100% Series 38 Flag (Great Britain)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S38+GB' },
      { id: 's38-horror', name: 'Bearbrick 100% Series 38 Horror (IT)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S38+IT' },
      { id: 's38-sf', name: 'Bearbrick 100% Series 38 SF (Robocop)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S38+Robo' },
      { id: 's38-cute', name: 'Bearbrick 100% Series 38 Cute (Garfield)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S38+Garfield' },
      { id: 's38-animal', name: 'Bearbrick 100% Series 38 Animal (Pingu)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S38+Pingu' },
      { id: 's38-artist1', name: 'Bearbrick 100% Series 38 Artist (Mishka)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S38+Artist' },
      { id: 's38-artist2', name: 'Bearbrick 100% Series 38 Artist (Lauren Tsai)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S38+Artist' },
      { id: 's38-secret-babymilo', name: 'Bearbrick 100% Series 38 Secret (BABY MILO)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S38+Secret' },
      { id: 's38-secret-assc', name: 'Bearbrick 100% Series 38 Secret (Anti Social Social Club)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S38+Secret' },
      { id: 's38-secret-joker', name: 'Bearbrick 100% Series 38 Secret (Joker Chase)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/1F2937/FFFFFF/png?text=S38+Secret' },
    ],
  },
  // =================================================================
  // PLUSHIE COLLECTIONS
  // =================================================================
  {
    id: 'pikachu-halloween-plushies',
    name: 'Pikachu Halloween Exclusives',
    description: 'A spooktacular collection of exclusive Halloween-themed Pikachu plushies from the Pokémon Center.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-h23-gengar', name: 'Gengar Hoodie Pikachu Plush (2023)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Gengar+Pika' },
      { id: 'pika-h23-mimikyu', name: 'Mimikyu Costume Pikachu Plush (2023)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Mimikyu+Pika' },
      { id: 'pika-h22-witch', name: 'Witch Hat Pikachu Plush (2022)', rarity: 'Uncommon', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Witch+Pika' },
      { id: 'pika-h22-vampire', name: 'Vampire Cape Pikachu Plush (2022)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Vampire+Pika' },
      { id: 'pika-h21-pumpkin', name: 'Pumpkin Pikachu Plush (2021)', rarity: 'Common', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Pumpkin+Pika' },
      { id: 'pika-h20-zombie', name: 'Zombie Pikachu Plush (2020)', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Zombie+Pika' },
      { id: 'pika-h19-mummy', name: 'Mummy Pikachu Plush (2019)', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Mummy+Pika' },
      { id: 'pika-h18-ghost', name: 'Ghost Sheet Pikachu Plush (2018)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Ghost+Pika' },
    ]
  },
  {
    id: 'pikachu-kyoto-exclusives',
    name: 'Pikachu Kyoto Exclusives',
    description: 'Special edition Pikachu plushies only available at the Pokémon Center Kyoto, featuring traditional themes.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-kyoto-maiko', name: 'Maiko Pikachu Plush', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Maiko+Pika' },
      { id: 'pika-kyoto-kuge', name: 'Kuge (Nobleman) Pikachu Plush', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Kuge+Pika' },
      { id: 'pika-kyoto-ho-oh', name: 'Ho-Oh Poncho Pikachu Plush', rarity: 'Uncommon', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Ho-Oh+Pika' },
      { id: 'pika-kyoto-ninja', name: 'Ninja Pikachu Plush', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Ninja+Pika' },
      { id: 'pika-kyoto-matcha', name: 'Matcha Sweets Pikachu Plush', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Matcha+Pika' },
    ]
  },
  {
    id: 'pikachu-osaka-exclusives',
    name: 'Pikachu Osaka DX Exclusives',
    description: 'Fun and quirky Pikachu plushies from the Pokémon Center Osaka DX, celebrating local culture.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-osaka-manzai', name: 'Manzai Comedian Pikachu Plush', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Manzai+Pika' },
      { id: 'pika-osaka-takoyaki', name: 'Takoyaki Vendor Pikachu Plush', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Takoyaki+Pika' },
      { id: 'pika-osaka-billiken', name: 'Billiken Pikachu Plush', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Billiken+Pika' },
      { id: 'pika-osaka-captain', name: 'Captain Pikachu (Sailor)', rarity: 'Common', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Captain+Pika' },
    ]
  },
  {
    id: 'pikachu-hiroshima-exclusives',
    name: 'Pikachu Hiroshima Exclusives',
    description: 'Unique Pikachu plushies from Pokémon Center Hiroshima, often featuring the local baseball team.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-hiro-carp', name: 'Hiroshima Toyo Carp Uniform Pikachu', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Carp+Pika' },
      { id: 'pika-hiro-gyarados', name: 'Red Gyarados-Riding Pikachu', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Gyarados+Pika' },
      { id: 'pika-hiro-momiji', name: 'Momiji Manju Pikachu Plush', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Momiji+Pika' },
      { id: 'pika-hiro-lemon', name: 'Setouchi Lemon Pikachu Plush', rarity: 'Common', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Lemon+Pika' },
    ]
  },
  {
    id: 'pikachu-sapporo-exclusives',
    name: 'Pikachu Sapporo Exclusives',
    description: 'Snowy and cool Pikachu plushies from the Pokémon Center Sapporo in Hokkaido.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-sapp-vulpix', name: 'Alolan Vulpix Poncho Pikachu', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Vulpix+Pika' },
      { id: 'pika-sapp-snow', name: 'Snow Festival Pikachu', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Snow+Pika' },
      { id: 'pika-sapp-clione', name: 'Clione Pikachu Plush', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Clione+Pika' },
      { id: 'pika-sapp-fox', name: '"Kitakitsune" Ezo Red Fox Pikachu', rarity: 'Common', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Fox+Pika' },
    ]
  },
  {
    id: 'pikachu-tohoku-exclusives',
    name: 'Pikachu Tohoku Exclusives',
    description: 'Wishful and festive Pikachu plushies from the Pokémon Center Tohoku.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-toho-jirachi', name: 'Jirachi Poncho Pikachu', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Jirachi+Pika' },
      { id: 'pika-toho-tanabata', name: 'Tanabata Festival Pikachu', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Tanabata+Pika' },
      { id: 'pika-toho-victini', name: 'Victini Poncho Pikachu', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Victini+Pika' },
      { id: 'pika-toho-rowlet', name: 'Rowlet Poncho Pikachu', rarity: 'Uncommon', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Rowlet+Pika' },
    ]
  },
  {
    id: 'pikachu-tokyo-dx-exclusives',
    name: 'Pikachu Tokyo DX Exclusives',
    description: 'Pikachu plushies celebrating Japanese culture, from the Pokémon Center Tokyo DX.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-tokyo-gentleman', name: 'Gentleman Pikachu Plush', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Gentleman+Pika' },
      { id: 'pika-tokyo-hakama', name: 'Hakama Professor Pikachu', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Hakama+Pika' },
      { id: 'pika-tokyo-firefighter', name: 'Hikeshi Firefighter Pikachu', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Fire+Pika' },
      { id: 'pika-tokyo-snorlax', name: 'Snorlax Bean Bag Pikachu', rarity: 'Common', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Snorlax+Pika' },
    ]
  },
  {
    id: 'pikachu-skytree-exclusives',
    name: 'Pikachu Skytree Town Exclusives',
    description: 'Legendary-themed Pikachu plushies from the Pokémon Center in the Tokyo Skytree.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-sky-rayquaza', name: 'Rayquaza Poncho Pikachu', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Rayquaza+Pika' },
      { id: 'pika-sky-rayquaza-shiny', name: 'Shiny Rayquaza Poncho Pikachu', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Shiny+Ray+Pika' },
      { id: 'pika-sky-in-the-sky', name: 'Pikachu in the Sky Plush', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Sky+Pika' },
      { id: 'pika-sky-mascot', name: 'Rayquaza Mascot Pikachu', rarity: 'Common', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Mascot+Pika' },
    ]
  },
  {
    id: 'pikachu-yokohama-exclusives',
    name: 'Pikachu Yokohama Exclusives',
    description: 'Nautical and adorable Pikachu plushies from the port city of Yokohama.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-yoko-sailor-blue', name: 'Sailor Pikachu Plush (Blue)', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Sailor+Pika' },
      { id: 'pika-yoko-captain', name: 'Captain Pikachu Plush', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Captain+Pika' },
      { id: 'pika-yoko-pirate', name: 'Pirate Pikachu Plush', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Pirate+Pika' },
      { id: 'pika-yoko-celebi', name: 'Celebi Poncho Pikachu', rarity: 'Secret', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Celebi+Pika' },
    ]
  },
  {
    id: 'pikachu-nagoya-exclusives',
    name: 'Pikachu Nagoya Exclusives',
    description: 'Plushies celebrating local legends from Pokémon Center Nagoya.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-nago-magikarp', name: 'Golden Magikarp Poncho Pikachu', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Magikarp+Pika' },
      { id: 'pika-nago-magikarp-shiny', name: 'Shiny Magikarp Poncho Pikachu', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Shiny+Karp+Pika' },
      { id: 'pika-nago-team-magma', name: 'Team Magma Poncho Pikachu', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Magma+Pika' },
      { id: 'pika-nago-team-aqua', name: 'Team Aqua Poncho Pikachu', rarity: 'Uncommon', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Aqua+Pika' },
    ]
  },
  {
    id: 'pikachu-kanazawa-exclusives',
    name: 'Pikachu Kanazawa Exclusives',
    description: 'Elegant Pikachu plushies celebrating traditional arts from Pokémon Center Kanazawa.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-kana-kaga-male', name: 'Kaga Kimono Pikachu (Male)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Kimono+Pika+M' },
      { id: 'pika-kana-kaga-female', name: 'Kaga Kimono Pikachu (Female)', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Kimono+Pika+F' },
      { id: 'pika-kana-milotic', name: 'Milotic Poncho Pikachu', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Milotic+Pika' },
      { id: 'pika-kana-opening', name: '"Kanazawa Opening" Pikachu', rarity: 'Uncommon', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Kanazawa+Pika' },
    ]
  },
  {
    id: 'pikachu-fukuoka-exclusives',
    name: 'Pikachu Fukuoka Exclusives',
    description: 'Festive and fun Pikachu plushies from the Pokémon Center Fukuoka.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-fuku-ludicolo', name: 'Ludicolo Poncho Pikachu', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Ludicolo+Pika' },
      { id: 'pika-fuku-bow-arrow', name: 'Bow & Arrow Pikachu', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Bow+Pika' },
      { id: 'pika-fuku-happi', name: 'Festival Happi Coat Pikachu', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Happi+Pika' },
      { id: 'pika-fuku-kyogre', name: 'Kyogre Poncho Pikachu', rarity: 'Rare', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Kyogre+Pika' },
    ]
  },
  {
    id: 'pikachu-okinawa-exclusives',
    name: 'Pikachu Okinawa Exclusives',
    description: 'Tropical and vibrant Pikachu plushies from Pokémon Center Okinawa.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-oki-kariyushi', name: 'Kariyushi Wear Pikachu', rarity: 'Common', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Kariyushi+Pika' },
      { id: 'pika-oki-arcanine', name: 'Arcanine Poncho Pikachu', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Arcanine+Pika' },
      { id: 'pika-oki-growlithe', name: 'Growlithe Poncho Pikachu', rarity: 'Uncommon', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Growlithe+Pika' },
      { id: 'pika-oki-blue-seal', name: 'Blue Seal Ice Cream Pikachu', rarity: 'Secret', owned: true, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Ice+Cream+Pika' },
    ]
  },
  {
    id: 'pikachu-singapore-exclusives',
    name: 'Pikachu Singapore Exclusives',
    description: 'Exclusive Pikachu plushies from the Pokémon Center at Jewel Changi Airport, Singapore.',
    category: CollectionCategory.PLUSHIES,
    items: [
      { id: 'pika-sg-pilot', name: 'Pilot Pikachu Plush', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Pilot+Pika' },
      { id: 'pika-sg-cabin-attendant', name: 'Cabin Attendant Pikachu Plush', rarity: 'Rare', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Cabin+Pika' },
      { id: 'pika-sg-lapras-poncho', name: 'Lapras Poncho Pikachu Plush', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Lapras+Pika' },
      { id: 'pika-sg-celebi-poncho', name: 'Celebi Poncho Pikachu Plush', rarity: 'Secret', owned: false, imageUrl: 'https://placehold.co/100x100/4B5563/FFFFFF/png?text=Celebi+Pika' },
    ]
  },
  // =================================================================
  // COIN & BANKNOTE COLLECTIONS (New Structure)
  // =================================================================
  {
    id: 'world-coins',
    name: 'World Coin Collection',
    description: 'Track the countries from which you have collected at least one coin.',
    category: CollectionCategory.COINS,
    items: createCountryItems('coin', ['us', 'ca', 'jp', 'fr', 'gb', 'mx', 'de']),
  },
  {
    id: 'world-banknotes',
    name: 'World Banknote Collection',
    description: 'Track the countries from which you have collected at least one banknote.',
    category: CollectionCategory.BANKNOTES,
    items: createCountryItems('banknote', ['us', 'ca', 'jp', 'ch', 'au', 'br', 'in']),
  },
  // =================================================================
  // OTHERS COLLECTION
  // =================================================================
  {
    id: 'others-custom',
    name: 'Other Collectibles',
    description: 'A custom collection for your other prized possessions. Add your own items!',
    category: CollectionCategory.OTHERS,
    items: [],
  },
];